# Generated by Django 4.0 on 2021-12-20 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_alter_user_name_alter_user_photo_and_more'),
        ('categories', '0004_alter_category_options_alter_subcategory_options_and_more'),
        ('posts', '0004_alter_comment_post_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.user', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='posts', to='accounts.user', verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='posts', to='categories.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='post',
            name='code',
            field=models.PositiveIntegerField(unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='posts/%Y/%m/%d', verbose_name='Imagem de publicação'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img_active',
            field=models.BooleanField(default=True, verbose_name='Imagem no post?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=256, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_categories',
            field=models.ManyToManyField(to='categories.SubCategory', verbose_name='Subcategorias'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Título'),
        ),
    ]
