# Generated by Django 4.0 on 2022-02-20 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_user_options_alter_user_name_alter_user_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategorySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('state', models.CharField(choices=[('invalid', 'INVÁLIDO'), ('reject', 'RECUSADO'), ('loading', 'EM ANDAMENTO'), ('accept', 'ACEITO')], max_length=256, verbose_name='Estado:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.user', verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='CategorySuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('state', models.CharField(choices=[('invalid', 'INVÁLIDO'), ('reject', 'RECUSADO'), ('loading', 'EM ANDAMENTO'), ('accept', 'ACEITO')], max_length=256, verbose_name='Estado:')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.user', verbose_name='Usuário')),
            ],
        ),
    ]
