# Generated by Django 4.0 on 2022-03-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_alter_user_name_alter_user_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_static_pages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
